import { route } from '@stacksjs/router'
import { healthResponse } from '../app/Support/health'

/**
 * This file is the entry point for your application's API routes.
 * The routes defined here are automatically registered. Last but
 * not least, you may also create any other `routes/*.ts` files.
 *
 * Framework routes (auth, dashboard, commerce, CMS, etc.) are loaded
 * automatically from storage/framework/defaults/routes/dashboard.ts.
 * You do NOT need to define them here — only add your own custom routes.
 *
 * @see https://docs.stacksjs.com/routing
 */

// No route.get('/', ...) here: static views win over programmatic routes
// at the same path in this router, so resources/views/index.stx always
// handles '/' regardless of what's registered here. Custom status page
// domains (stacksjs/status#1 Phase 7) are resolved inside that view's
// own <script server> block instead — see the comment at the top of
// resources/views/index.stx for why.

// Monitor CRUD (index/show/update/destroy) is auto-generated by the
// `useApi` trait on app/Models/Monitor.ts. `store` is overridden here
// (user-defined routes take priority over the auto-generated ones) to
// enforce the team's plan limit before creating — see
// Actions/Monitors/CreateMonitorAction. Custom action: triggering an
// out-of-band check outside the scheduler's normal cadence.
route.post('/monitors', 'Actions/Monitors/CreateMonitorAction')
route.post('/monitors/{id}/check', 'Actions/Monitors/RunCheckAction')

// Incident index/show are auto-generated by the `useApi` trait on
// app/Models/Incident.ts. store and update are overridden: Incident has no
// team_id of its own — its team is its monitor's or its server's — and the
// generated store/update accept any monitor_id / server_id, which through
// observe:true would page that row's team with the caller's text.
// Custom action: a one-step acknowledge, since update requires PATCHing the
// full resource with a status string.
route.post('/incidents', 'Actions/Incidents/CreateIncidentAction')
route.patch('/incidents/{id}', 'Actions/Incidents/UpdateIncidentAction')
route.post('/incidents/{id}/acknowledge', 'Actions/Incidents/AcknowledgeIncidentAction')

// TeamMember index/show/destroy is auto-generated by the `useApi` trait on
// app/Models/TeamMember.ts. Custom actions: creating a member is always an
// invite (pending until accepted), and acceptance links a real user id.
route.post('/teams/{id}/invite', 'Actions/Teams/InviteTeamMemberAction')
route.post('/team-invites/{uuid}/accept', 'Actions/Teams/AcceptTeamInviteAction')

// Browser-facing invite acceptance: the invite email links to the page at
// resources/views/invite/[uuid].stx, whose form posts here. Unlike the
// JSON accept above it links-or-registers the user, activates the
// membership, and mints a session cookie (see AcceptInviteFormAction).
// Rate-limited: the uuid is a bearer capability, so throttle guessing.
route.post('/invite-forms/{uuid}/accept', 'Actions/Teams/AcceptInviteFormAction').rateLimit(10, 'minute')

// Public heartbeat ping endpoint (no auth — the token itself is the secret).
// GET *and* POST both work since cron jobs commonly just `curl` the URL.
// .skipCsrf() on the POST variant: this is hit by external cron jobs/curl,
// never a browser form post, so it can never carry a CSRF token — without
// this it 403s "CSRF token mismatch" on every POST (confirmed broken as of
// stacksjs/status#1, discovered while adding the metrics endpoint below).
route.get('/ping/{token}', 'Actions/Heartbeats/ReceivePingAction')
route.post('/ping/{token}', 'Actions/Heartbeats/ReceivePingAction').skipCsrf()
// Optional /start and /fail sub-pings: a job can bracket its run to measure
// duration and report an explicit non-zero exit. Same action, keyed on {kind}.
route.get('/ping/{token}/{kind}', 'Actions/Heartbeats/ReceivePingAction')
route.post('/ping/{token}/{kind}', 'Actions/Heartbeats/ReceivePingAction').skipCsrf()

// Public agent metrics ingest endpoint (no auth — servers.metrics_token IS
// the auth, same unguessable-token pattern as /ping/{token} above). A
// customer's own monitored box pushes CPU/RAM samples here on its own
// cron cadence; we don't poll for this data, it's push-only. Same
// .skipCsrf() reasoning as the ping POST route above.
route.post('/agent/{token}/metrics', 'Actions/Agents/ReceiveMetricsAction').skipCsrf()

// Regional probe fleet (stacksjs/status#1 Phase 11, push-probe topology).
// A remote check region (e.g. the Ashburn/us-east worker) has no shared DB:
// it pulls the monitors to probe, runs the checks locally, and POSTs the
// region-tagged results back here, where EvaluateMonitorConsensus weighs
// them for cross-region agreement. Auth is the unguessable
// REGIONAL_INGEST_TOKEN in the URL — same token-is-the-secret pattern as
// /ping and /agent above; .skipCsrf() for the same server-to-server reason.
// GET /status is read-only introspection used to verify the fleet e2e.
route.get('/regions/{token}/monitors', 'Actions/Regions/ListRegionMonitorsAction')
route.post('/regions/{token}/results', 'Actions/Regions/IngestRegionResultsAction').skipCsrf()
route.get('/regions/{token}/status', 'Actions/Regions/RegionStatusAction')

// StatusPage CRUD (index/show/update/destroy) is auto-generated by the
// `useApi` trait on app/Models/StatusPage.ts. `store` is overridden here,
// same pattern as CreateMonitorAction, to enforce the team's plan limit.
route.post('/status-pages', 'Actions/StatusPages/CreateStatusPageAction')

// One-time migration from an existing Better Stack/Instatus/Statuspage.io
// page (stacksjs/status#1 Phase 12).
route.post('/status-pages/import', 'Actions/StatusPages/ImportStatusPageAction')

// StatusReportUpdate index/show is auto-generated by the `useApi` trait on
// app/Models/StatusReportUpdate.ts. `store` is overridden here because the
// generated store handler inserts via raw db writes that fire no model
// events — posting an update must emit 'statusreportupdate:created' so
// status page subscribers get emailed (stacksjs/status#1 Phase 12
// follow-up; see Actions/StatusPages/CreateStatusReportUpdateAction).
route.post('/status-report-updates', 'Actions/StatusPages/CreateStatusReportUpdateAction')

// Password/email-domain gate for access-controlled status pages
// (stacksjs/status#1 Phase 12) — public, no auth (this route IS the auth).
// Rate-limited: this endpoint verifies a password/allowed email, so throttle
// brute-force guessing the same way the login/2FA routes below are throttled.
route.post('/status/{slug}/unlock', 'Actions/StatusPages/UnlockStatusPageAction').rateLimit(5, 'minute')

// Status page subscriber signup/unsubscribe — public, no auth. Rate-limited:
// subscribe sends a confirmation email (so throttle mail-flood / signup spam),
// and unsubscribe takes a bearer token in the URL (throttle token guessing).
route.post('/status/{slug}/subscribe', 'Actions/StatusPages/SubscribeAction').rateLimit(10, 'minute')
route.get('/status/{slug}/unsubscribe/{token}', 'Actions/StatusPages/UnsubscribeAction').rateLimit(10, 'minute')
route.get('/status/{slug}/feed', 'Actions/StatusPages/IncidentFeedAction')

// Dashboard status-page builder form posts (stacksjs/status#1 Phase 8) —
// plain POST + redirect, not the JSON-returning API actions above, since
// these back native HTML <form> elements with no client JS (see
// Actions/StatusPages/UpdateStatusPageAction for why). Deliberately NOT
// under /dashboard/status-pages/* — that collides with the dynamic file
// route resources/views/dashboard/status-pages/[id].stx (e.g. a POST to
// .../create matches [id]="create" as a GET-only view route first and
// 405s) — same "static/dynamic views win over routes at the same path"
// behavior documented at the top of this file, just for a dynamic [id]
// route instead of a static one this time.
route.post('/status-page-forms/create', 'Actions/StatusPages/DashboardCreateStatusPageAction')
route.post('/status-page-forms/{id}/update', 'Actions/StatusPages/UpdateStatusPageAction')
route.post('/status-page-forms/{id}/monitors/add', 'Actions/StatusPages/DashboardAssignMonitorAction')
route.post('/status-page-forms/{id}/monitors/remove', 'Actions/StatusPages/DashboardRemoveMonitorAction')

// Status-report (manual announcement) authoring form posts (stacksjs/
// status#1 Phase 12 follow-up — the dashboard surface that was missing, so
// a report + its monitor pivots could only be created by curling the API).
// Same /*-forms/ prefix convention (not /dashboard/status-reports/*, which
// would collide with the dynamic [id] view). Posting an update fires the
// StatusReportUpdate observe hook that emails status page subscribers.
route.post('/status-report-forms/create', 'Actions/StatusPages/DashboardCreateStatusReportAction')
route.post('/status-report-forms/{id}/monitors/add', 'Actions/StatusPages/DashboardAttachReportMonitorAction')
route.post('/status-report-forms/{id}/monitors/remove', 'Actions/StatusPages/DashboardRemoveReportMonitorAction')
route.post('/status-report-forms/{id}/updates', 'Actions/StatusPages/DashboardPostReportUpdateAction')
route.post('/status-report-forms/{id}/delete', 'Actions/StatusPages/DashboardDeleteStatusReportAction')

// Maintenance-window form posts. The model has carried an auto-generated
// CRUD API (`/maintenance-windows`) since Phase 12 and the suppression
// logic, status job and subscriber notices were all built against it, but
// nothing in the product ever posted to it — no view, no form, no nav
// entry — so scheduling announced downtime meant curl, while
// docs/operate/maintenance.md told operators to click a button that did
// not exist. Same /*-forms/ prefix as the routes above, for the same
// dynamic-view-collision reason.
route.post('/maintenance-forms/create', 'Actions/Maintenance/DashboardCreateMaintenanceWindowAction')
route.post('/maintenance-forms/{id}/update', 'Actions/Maintenance/DashboardUpdateMaintenanceWindowAction')
route.post('/maintenance-forms/{id}/delete', 'Actions/Maintenance/DashboardDeleteMaintenanceWindowAction')
route.post('/maintenance-forms/{id}/monitors/add', 'Actions/Maintenance/DashboardAttachMaintenanceMonitorAction')
route.post('/maintenance-forms/{id}/monitors/remove', 'Actions/Maintenance/DashboardRemoveMaintenanceMonitorAction')

// Dashboard notification-channel form posts (stacksjs/status#1 Phase 8) —
// same plain-POST convention, and same /*-forms/ naming to dodge the
// dynamic-view-collision explained above (there's no [id].stx under
// dashboard/settings, but keeping the convention consistent avoids
// having to remember which pages need the workaround).
route.post('/notification-channel-forms/create', 'Actions/Notifications/DashboardCreateChannelAction')
route.post('/notification-channel-forms/{id}/test-send', 'Actions/Notifications/DashboardTestSendAction')
// One submit saves a monitor's whole routing grid. The per-channel
// assign/remove pair this replaces is gone rather than kept alongside:
// two write paths to the same pivot is how fires_on drifts.
route.post('/notification-channel-forms/monitors/{monitorId}/routing', 'Actions/Notifications/DashboardSaveRoutingAction')

// Monitor create/edit/delete form posts — the no-JS counterparts to
// POST /monitors, so the product can be set up without curl. Same
// plain-POST, team-scoped convention as the form routes below; the create
// path enforces the same plan limits as the JSON action.
route.post('/monitor-forms/create', 'Actions/Monitors/DashboardCreateMonitorAction')
route.post('/monitor-forms/{monitorId}/update', 'Actions/Monitors/DashboardUpdateMonitorAction')
route.post('/monitor-forms/{monitorId}/delete', 'Actions/Monitors/DashboardDeleteMonitorAction')

// Server form posts. The same /*-forms/ prefix as the monitor block above,
// and for a mechanical reason: dashboard/servers/[id].stx would collide with
// /dashboard/servers/*. Every action is team-scoped through servers.team_id
// and, where a monitor is named, monitors.team_id as well.
//
// There is deliberately no generated PATCH or DELETE /servers/{id}: the
// generated update filters by `fillable` alone, which would let a caller set
// status or last_sample_at, and the generated destroy deletes only the row,
// leaving detached monitors, orphaned samples and open incidents behind.
route.post('/servers', 'Actions/Servers/CreateServerAction')
route.post('/server-forms/create', 'Actions/Servers/DashboardCreateServerAction')
route.post('/server-forms/{serverId}/update', 'Actions/Servers/DashboardUpdateServerAction')
route.post('/server-forms/{serverId}/delete', 'Actions/Servers/DashboardDeleteServerAction')
route.post('/server-forms/{serverId}/rotate-token', 'Actions/Servers/DashboardRotateServerTokenAction')
route.post('/server-forms/{serverId}/monitors', 'Actions/Servers/DashboardSaveServerMonitorsAction')
route.post('/server-forms/monitors/{monitorId}/server', 'Actions/Servers/DashboardAttachServerAction')

// Response-assertion form posts on the monitor detail page (dot-path health
// assertions and header/status/response-time checks) — same plain-POST,
// team-scoped convention as the notification-channel forms above.
route.post('/assertion-forms/monitors/{monitorId}/add', 'Actions/Assertions/DashboardCreateAssertionAction')
route.post('/assertion-forms/monitors/{monitorId}/remove', 'Actions/Assertions/DashboardRemoveAssertionAction')

// Dashboard team settings form posts (stacksjs/status#1 Phase 8) — same
// plain-POST convention.
route.post('/team-forms/{id}/invite', 'Actions/Teams/DashboardInviteTeamMemberAction')
route.post('/team-forms/{id}/remove', 'Actions/Teams/DashboardRemoveTeamMemberAction')
// Promote/demote without revoking access: before this, changing a role meant
// removing the member and re-inviting them.
route.post('/team-forms/{id}/role', 'Actions/Teams/DashboardUpdateTeamMemberRoleAction')

// Workspace switcher: pin which team the dashboard scopes to. The cookie it
// sets is re-validated against the requester's memberships on every request
// (see @stacksjs/auth resolveTeamContext / selectActiveTeam), so it can't be
// used to reach a team the user isn't in.
route.post('/team-forms/switch', 'Actions/Teams/SwitchTeamAction')

// Security settings form posts (stacksjs/status#1 Phase 9 follow-up —
// the passkey/2FA dashboard UI deferred until real dashboard auth
// existed). Same plain-POST convention; each action resolves the
// requester from their real credential (resolveAuthenticatedUser) since
// native form posts carry only the login cookie, no bearer header.
route.post('/security-forms/two-factor/enable', 'Actions/Security/DashboardEnableTwoFactorAction')
route.post('/security-forms/two-factor/disable', 'Actions/Security/DashboardDisableTwoFactorAction')
route.post('/security-forms/passkeys/delete', 'Actions/Security/DashboardDeletePasskeyAction')

// Passkey (WebAuthn) enrollment + passwordless sign-in (stacksjs/status#1
// Phase 9 follow-up). Enrollment resolves the signed-in user from the
// auth-token cookie (NOT the bearer/session Auth middleware, which a
// dashboard fetch can't satisfy); sign-in is unauthenticated and mints a
// session on success. Verification is app-owned and spec-correct — see
// Actions/Security/webauthn.ts for why it doesn't use ts-auth's verifiers.
// All four are CSRF-protected (the client sends the double-submit token).
route.post('/passkeys/register/options', 'Actions/Security/PasskeyRegisterOptionsAction')
route.post('/passkeys/register/verify', 'Actions/Security/PasskeyRegisterVerifyAction')
route.post('/passkeys/login/options', 'Actions/Security/PasskeyLoginOptionsAction')
route.post('/passkeys/login/verify', 'Actions/Security/PasskeyLoginVerifyAction')

// Billing (stacksjs/status#1 Phase 9). /checkout is a dashboard form
// post, same convention as the rest of this block. /webhook is called
// by Stripe itself — no CSRF token to satisfy (skipCsrf, matching the
// storefront/contact-form precedent above), and its own signature
// verification (StripeWebhookAction) is the real security control.
route.post('/billing-forms/checkout', 'Actions/Billing/CreateCheckoutSessionAction')
route.post('/billing-forms/cancel', 'Actions/Billing/CancelSubscriptionAction')
route.post('/billing-forms/webhook', 'Actions/Billing/StripeWebhookAction').name('billing.webhook').skipCsrf()

// Auth overrides — user routes win over storage/framework/defaults/
// routes/dashboard.ts's copies. Same login/2FA/logout flow, plus
// mirroring the bearer into an HttpOnly cookie so the server-rendered
// dashboard (resources/views/dashboard/*.stx) can resolve the current
// user/team during SSR — see Actions/Auth/LoginAction's doc comment.
route.post('/login', 'Actions/Auth/LoginAction').rateLimit(5, 'minute')
route.post('/register', 'Actions/Auth/RegisterAction').rateLimit(3, 'minute')
route.post('/verify-two-factor-login', 'Actions/Auth/VerifyTwoFactorLoginAction').rateLimit(10, 'minute')
route.post('/logout', 'Actions/Auth/LogoutAction').middleware('auth')

// Single sign-on (authorization code + PKCE). GET on purpose —
// both legs are full-page browser navigations driven by the IdP, not
// XHR calls, so they live outside the SPA token flow entirely and mint
// the same HttpOnly cookie session LoginAction does. Providers are
// configured per install in config/sso.ts: social login via
// @stacksjs/socials (Google, Apple, GitHub) and enterprise OIDC (Okta,
// Entra ID, or any spec-compliant issuer via the generic entry).
route.get('/auth/sso/{provider}', 'Actions/Auth/SsoRedirectAction').rateLimit(10, 'minute')
route.get('/auth/sso/{provider}/callback', 'Actions/Auth/SsoCallbackAction').rateLimit(10, 'minute')
// Apple mandates response_mode=form_post when name/email scopes are
// requested, so its callback arrives as a cross-site POST from
// appleid.apple.com — it can never carry our CSRF cookie/header pair.
// skipCsrf is safe here: the signed sso-flow cookie + state parameter
// are this flow's CSRF protection (that's exactly what OAuth state is).
route.post('/auth/sso/{provider}/callback', 'Actions/Auth/SsoCallbackAction').rateLimit(10, 'minute').skipCsrf()

// Cloud credentials: dashboard settings form post (same /*-forms/ convention).
// Stores the team's AWS credentials (secret encrypted at rest) for the
// metrics-agent provisioning automation — see Actions/Cloud/SaveAwsCredentialsAction.
route.post('/cloud-credential-forms/aws', 'Actions/Cloud/SaveAwsCredentialsAction')

// Per-team uptime report emails: dashboard settings form post (same
// /*-forms/ convention as the blocks above; see
// app/Jobs/SendUptimeReports.ts for the scheduled sender).
route.post('/team-forms/{id}/report-settings', 'Actions/Teams/DashboardUpdateReportSettingsAction')

// `/coming-soon` is served as an STX view from
// `storage/framework/defaults/resources/views/coming-soon.stx`. The
// view auto-resolves through stx-serve, so no route registration is
// needed here. To activate the holding page across the whole app:
//
//   ./buddy coming-soon [--secret=my-magic-token]
//
// Launch the site with `./buddy launch`. Maintenance mode (503 page,
// distinct cookie + state file) is the separate `./buddy down` /
// `./buddy up` pair.

// ---------------------------------------------------------------------------
// Health
// ---------------------------------------------------------------------------

// This app already answers /api/health, but only because it happens to satisfy
// both of the framework's unrelated preconditions: the dashboard is enabled in
// config, and it is the one app in the fleet that tracks storage/framework/ in
// git, so the vendored defaults/routes/dashboard.ts that calls route.health()
// actually reaches the box. Gitignoring that tree — which every sibling does —
// would silently remove the endpoint.
//
// Registering it here makes the monitor's target a property of this app rather
// than of a build artifact, and there is a particular reason it matters here:
// this is the app that watches the others. A status page whose own health check
// can vanish when someone changes an unrelated config flag is the wrong thing to
// build the fleet's monitoring on. See app/Support/health.ts.
//
// User routes load before the framework's, so this wins over route.health().
route.get('/health', () => healthResponse())
route.get('/api/health', () => healthResponse())
